user-message: "WARNING: This stack project is generated."

ghc-options:
  "$locals": -fhide-source-paths -Wno-missing-home-modules
nix:
  packages:
  - pkg-config
  - zlib

resolver: lts-21.7

# We have 4 packages.
packages:
  - ./.
  - ./pandoc-cli
  - ./pandoc-lua-engine
  - ./pandoc-server

# We have 1 internal dependency source package.
extra-deps:
  # Source Packages, internal to this organisation (private and public).
  - git: https://github.com/jgm/typst-hs
    commit: 71c24946e098ce8af0b8de4004711e4ee732f2d0

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - commonmark-0.2.4
  - commonmark-extensions-0.2.4
  - crypton-connection-0.3.1
  - crypton-x509-1.7.6
  - crypton-x509-store-1.6.9
  - crypton-x509-system-1.6.7
  - crypton-x509-validation-1.6.12
  - hslua-cli-1.4.1
  - hslua-module-zip-1.1.0
  - hslua-repl-0.1.1
  - http-client-tls-0.3.6.3
  - lpeg-1.1.0
  - skylighting-0.14
  - skylighting-core-0.14
  - skylighting-format-blaze-html-0.1.1.1
  - texmath-0.12.8.4
  - tls-1.9.0
  - toml-parser-1.3.0.0
  - typst-symbols-0.1.4
